cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - venv/
  policy: pull

stages:
  - install
  - build
  - lint
  - test
  - deploy

before_script:
  - source venv/bin/activate

Install dependencies:
  stage: install
  cache:
    <<: *global_cache
    policy: pull-push
  variables:
    PIP_INDEX_URL: "https://mirror.p.lksh.ru/pypi/simple"
    PIP_INSTALL_OPTIONS: "--jobs=16"
  before_script:
    - if [ ! -d venv ]; then python -m venv venv; fi
    - source venv/bin/activate
  script:
    - pip install -r bot/requirements.txt
    - pip install -r ejudge_scraper/requirements.txt
    - pip install -r tlm/requirements.txt
    - pip install -r requirements-ci.txt

Build TLM schema:
  stage: build
  script:
    - python ci/build_schema.py tlm/openapi.yaml ci/openapi.json
  artifacts:
    paths:
      - ci/openapi.json

.lint_python: &lint_python
  - |
    for item in ${EXCLUDED_DIRECTORIES[*]}; do
      EXCLUDED_DIRECTORIES_ARGS="$EXCLUDED_DIRECTORIES_ARGS -path $item -prune -o"
    done
  - LINTED_FILES=$(find . $EXCLUDED_DIRECTORIES_ARGS -name '*.py' -print)
  - pylint --rcfile=$CI_PROJECT_DIR/.pylintrc $LINTED_FILES

Lint Bot:
  stage: lint
  script:
    - cd bot
    - *lint_python
Lint TLM:
  stage: lint
  script:
    - cd tlm
    - EXCLUDED_DIRECTORIES=(./db/migrations)
    - *lint_python
Lint Ejudge scraper:
  stage: lint
  script:
    - cd ejudge_scraper
    - *lint_python

Lint TLM schema:
  dependencies:
    - Build TLM schema
  stage: lint
  script:
    - cd ci
    - spectral lint openapi.json

Test Python:
  stage: test
  script:
    - pytest

.deploy_setup:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config'
    - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)

.deploy_staging:
  extends: .deploy_setup
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH == "ci-cd"
      when: manual
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH != "ci-cd"
      when: never

Deploy TLM schema:
  dependencies:
    - Build TLM schema
  extends: .deploy_staging
  script:
    - scp ci/openapi.json $DEPLOY_USER@$SSH_SCHEMA_HOST:$SCHEMA_DEPLOY_PATH

Deploy stub:
  extends: .deploy_staging
  script:
    - cd ci
    - ansible-playbook -i $SSH_HOST, deploy-stub.yml
