# Generated by Django 3.2.4 on 2021-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('cid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('last_run_id', models.BigIntegerField(null=True)),
            ],
        ),
    ]
