# Generated by Django 3.2.4 on 2021-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='last_run_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
