# Generated by Django 3.2.4 on 2021-07-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_contest_last_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='chat_id',
        ),
    ]
