# Generated by Django 3.2.4 on 2021-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField()),
                ('rid', models.BigIntegerField()),
                ('login', models.CharField(max_length=255)),
                ('problem', models.CharField(max_length=255)),
                ('status', models.CharField(default='unassigned', max_length=20)),
                ('assignee', models.BigIntegerField(null=True)),
                ('chat_id', models.BigIntegerField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('sent_to_chat', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('cid', 'login', 'problem')},
            },
        ),
    ]
