# Generated by Django 3.2.4 on 2021-07-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='chat_rid',
            field=models.BigIntegerField(null=True),
        ),
    ]
