# Generated by Django 3.2.4 on 2021-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm', '0002_submission_chat_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
