# Generated by Django 3.2.4 on 2021-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm', '0003_submission_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='link',
        ),
        migrations.AddField(
            model_name='submission',
            name='judge_link',
            field=models.CharField(default='http://ejudge.lksh.ru/placeholder.mp4', max_length=255),
            preserve_default=False,
        ),
    ]
