# Generated by Django 3.2.4 on 2021-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm', '0005_auto_20210726_1142'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_cid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cid',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
