# Generated by Django 3.2.4 on 2021-07-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlm', '0006_auto_20210726_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assignee',
            new_name='target_chat_id',
        ),
    ]
