# Generated by Django 3.2.5 on 2021-07-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlm', '0008_submission_snooze_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='snooze_time',
            new_name='last_snooze_time',
        ),
    ]
